/// Initial values written only when the corresponding setting is absent.
///
/// Keep this map aligned with the default configuration shipped by the app.
const Map<String, Object> defaultSettingValues = {
  'alwaysExapndIntroPanel': false,
  'angleDegrees': 50,
  'antiGoodsDyn': false,
  'antiGoodsReply': false,
  'appFontWeight': -1,
  'autoUpdate': false,
  'barHideType': 1,
  'biliProgressTimeStyle': true,
  'biliSendCommAntifraud': true,
  'blockSettings': <int>[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
  'blockUserID': '55cb0f972a338d2904f155eb87b721a2',
  'brightnessGestureAngleThreshold': 25.0,
  'brightnessGestureSpeed': 2.0,
  'btmProgressBehavior': 3,
  'bufferSec': 60.0,
  'bufferSize': 128.0,
  'cardRadius': 5.0,
  'cdnSpeedTest': true,
  'checkDynamic': true,
  'collapsedReplyFontScale': 0.95,
  'continuePlayInBackground': false,
  'customColor': 13,
  'customMpvOptions': '--dscale=ewa_robidoux\n'
      '--scale=ewa_robidoux\n'
      '--cscale=ewa_robidoux\n'
      '--deband-grain=0\n'
      '--deband-iterations=2\n'
      '--deband-threshold=12\n'
      '--deband\n'
      '--audio-delay=-0.1',
  'customPrimarySeed': 4278216191,
  'customSecondarySeed': 4294946760,
  'customTertiarySeed': 2566913792,
  'customThemeTone.light.card': 4.0,
  'customThemeTone.light.page': -2.0,
  'customThemeTone.light.primaryAccent': 20.0,
  'customThemeTone.light.secondaryAccent': 25.0,
  'customThemeTone.light.selected': 2.0,
  'customThemeTone.light.tertiaryAccent': 20.0,
  'danmakuBlockType': <int>[],
  'danmakuDuration': 7.0,
  'danmakuFixedV': false,
  'danmakuFontScale': 0.6,
  'danmakuFontScaleFS': 0.8,
  'danmakuLineHeight': 1.3,
  'danmakuMassiveMode': false,
  'danmakuOpacity': 0.9,
  'danmakuShowArea': 1.0,
  'danmakuStatic2Scroll': false,
  'danmakuStaticDuration': 4.0,
  'danmakuWeight': 0,
  'darkVideoPage': false,
  'defaultAudioQaCellular': 30251,
  'defaultVideoQa': 120,
  'defaultVideoQaCellular': 120,
  'defaultVideoQaHalfScreen': 120,
  'displayMode': '#2 1272x2800 @ 144Hz',
  'dynamicBadgeMode': 0,
  'dynamicColor': false,
  'enableAi': true,
  'enableAutoExit': false,
  'enableBackgroundPlay': false,
  'enableCommAntifraud': true,
  'enableCreateDynAntifraud': true,
  'enableDragSubtitle': true,
  'enableImgMenu': true,
  'enableLivePhoto': false,
  'enableMYBar': false,
  'enableOnlineTotal': true,
  'enableQuickDouble': false,
  'enableSearchRcmd': false,
  'enableSearchWord': true,
  'enableShowDanmaku': true,
  'enableShrinkVideoSize': false,
  'enableSlideFS': false,
  'enableSponsorBlock': false,
  'enableTapDm': false,
  'externalVideoLinkOpenInDetail': false,
  'fontWeight': 4,
  'fullScreenMode': 0,
  'homeTabBarHeight': 36.0,
  'horizontalScreen': false,
  'horizontalSeekGestureAngleThreshold': 45.0,
  'horizontalSeekGestureThreshold': 5.0,
  'legacyBottomBarBottomPadding': 35.0,
  'liveQualityCellular': 10000,
  'longPressSpeedToastVerticalPercent': 26.0,
  'longPressSpeedTriggerDelay': 400,
  'mergeDanmaku': false,
  'mpvLogLevel': 'v',
  'msgBadgeMode': 0,
  'openClipboardLinkOnResume': false,
  'openInBrowser': true,
  'optTabletNav': false,
  'pinchGestureAngleThreshold': 30.0,
  'pipNoDanmaku': true,
  'playerControlBarGradientExtent': 8.0,
  'playerControlBarThicknessScale': 1.4,
  'playerControlDisplayDurationSeconds': 5,
  'playerControlHorizontalPadding': 10.0,
  'playerGestureToastFontSize': 16.0,
  'playerGestureToastVerticalPercent': 26.0,
  'playerProgressBarTouchPadding': 10.0,
  'playerProgressThumbScale': 1.3,
  'preInitPlayer': true,
  'preferCodecs': <String>['AV1', 'HEVC', 'AVC'],
  'rcmdRefreshCount': 9,
  'recommendCardHorizontalPadding': 5.0,
  'recommendCardHorizontalSpacing': 5.0,
  'recommendCardVerticalSpacing': 5.0,
  'recommendDurationInStatRow': false,
  'recommendStatSpacing': 15.0,
  'recordSearchHistory': true,
  'refreshDragPercentage': 0.2,
  'removeSafeArea': false,
  'replyFontSize': 15.0,
  'replyLineSpacingScale': 0.85,
  'schemeVariant': 14,
  'seekPreviewFollowGesture': true,
  'seekPreviewFollowSlider': true,
  'seekPreviewProgressBarGap': 25.0,
  'seekPreviewScale': 0.8,
  'seekPreviewVerticalPosition': 60.0,
  'seekTimeInPreview': true,
  'seekTimeToastFontSize': 9.0,
  'seekTimeToastVerticalPercent': 5.0,
  'showDynDispute': true,
  'showFSActionItem': false,
  'showFsLockBtn': false,
  'showFsScreenshotBtn': false,
  'showHotRcmd': true,
  'showSeekPreviewOnGesture': true,
  'showSeekPreviewOnSlider': true,
  'sliderOffset': 50,
  'springDescription': <double>[1.0, 400.64908449286037, 40.0],
  'strokeWidth': 1.0,
  'subtitleBgOpaticy': 0.67,
  'subtitleFontScale': 1.0,
  'subtitleFontScaleFS': 1.5,
  'subtitleFontWeight': 5,
  'subtitlePaddingB': 10,
  'subtitlePaddingH': 24,
  'subtitleStrokeWidth': 2.0,
  'tabSwipeDistanceThresholdPercent': 20.0,
  'tabSwipeVelocityThreshold': 40.0,
  'textScale': 1.0,
  'themeColorMode': 2,
  'themeMode': 2,
  'touchSlopH': 8.0,
  'upPanelPosition': 0,
  'useRelativeSlide': true,
  'videoDetailUseAv': false,
  'verticalFullscreenBottomBarSafeArea': true,
  'verticalFullscreenBottomBarSafeHeight': 30.0,
  'verticalScrollDecelerationScale': 0.4,
  'verticalScrollInertiaScale': 1.0,
  'volumeGestureAngleThreshold': 25.0,
  'volumeGestureProgressBar': true,
  'volumeGestureSpeed': 0.5,
};

const Map<String, Object> defaultVideoValues = {
  'longPressSpeedDefault': 3.0,
  'speedsList': <double>[0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 3.0, 4.0],
};
